clear;
clc;

addpath(fullfile(pwd, '..', '..', 'numMVPA_analysis', 'code', 'lib', 'bidspm'));
bidspm();

this_dir = fileparts(mfilename('fullpath'));
root_dir = fullfile(this_dir, '..');

% bids_dir = fullfile(root_dir, 'inputs', 'raw');
bids_dir = '/Users/yiyang/DATA/numMVPA_bids/input/raw';
% fmriprep_dir = fullfile(root_dir, 'inputs', 'fmriprep');
fmriprep_dir = '/Volumes/ssd/fmriprep'; %fullfile(root_dir, 'inputs', 'fmriprep');
%'/Users/yiyang/DATA/numMVPA_fmriprep/outputs/derivatives/bidspm-preproc';
% output_dir = fullfile(root_dir, 'outputs', 'derivatives');
output_dir ='/Volumes/ssd/num_output/derivatives';%'/Volumes/ssd/num_output/derivatives';
model_file = '/Users/yiyang/DATA/numMVPA_fmriprep/code/models/model-numerosity_univariate_smdl.json';
preproc_dir = '/Users/yiyang/DATA/numMVPA_fmriprep/outputs/derivatives/bidspm-preproc';
subject_label = {'02','03','04','05','06','07','08','09','10','11','12',...
    '14','15','16','17','18','19','20','21','22','23'};%'02','03','04','05','06',
% subject_label = {'07','09','11',...
%     '14','16','18','19','20','21','22','23'};%'02','03','04','05','06',
% subject_label = {'02'};%,'18',
task = {'numMVPA'}; %'wordLocalizer'
space = {'MNI152NLin2009cAsym'};

%% subject level

opt.results(1).nodeName = 'subject_level';
opt.results(1).name = {'audnum_gt_baseline', 'audseq_gt_baseline',...
    'visnum_gt_baseline','visseq_gt_baseline','vissim_gt_baseline',...
    'audnum_gt_else', 'audseq_gt_else',...
    'visnum_gt_else','visseq_gt_else','vissim_gt_else',...
    'aud_gt_vis', 'vis_gt_aud', 'visnum_gt_vissim'};
opt.results(1).png = true();
opt.results(1).nidm = true();
opt.results(1).csv = true();
opt.results(1).p = 0.01;
opt.results(1).MC = 'none';
opt.results(1).threshSpm = true();
opt.results(1).binary = true();
opt.results(1).montage.do = true();
opt.results(1).montage.background = struct('suffix', 'T1w', ...
                                           'desc', 'preproc', ...
                                           'modality', 'anat');
opt.results(1).montage.slices = -4:2:16;

% run the stats at subject-level
% where the smooth data is
% preproc_dir = fullfile(output_dir, 'bidspm-preproc');
parfor i = 1:length(subject_label)
    bidspm(bids_dir, output_dir, 'subject', ...
           'participant_label', subject_label(i), ...
           'action', 'stats', ...
           'task', task,...
           'preproc_dir', preproc_dir, ...
           'model_file', model_file,...
           'space', space, ...
           'fwhm', 6,...
           'options', opt, ...
           'verbosity', 3);
end

%% group-level analyses for the localizers

% for group-level analyses with confwhm ~=0, a new pull request was merged with bidspm , 
% hence I made a new repo which is here: 

addpath('/Users/yiyang/DATA/groupsmoothing/bidspm')
bidspm();

%group-level GLm and contrasts - RESULTS to do separately

opt.fwhm.contrast = 6;

bidspm(bids_dir, output_dir, 'dataset', ...
       'participant_label', subject_label, ...
       'action', 'stats', ...
       'preproc_dir', preproc_dir, ...
       'model_file', model_file,...
       'task', task,...
       'space', space, ...
       'fwhm', 6,...
       'ignore', {'qa','concat'},...
       'concatenate', false,...
       'options', opt);

%visualize results
results = defaultResultsStructure();
results.nodeName = 'dataset_level';
results.name = {'audnum_gt_else', 'audseq_gt_else',...
    'visnum_gt_else','visseq_gt_else','vissim_gt_else',...
    'aud_gt_vis', 'vis_gt_aud', 'visnum_gt_vissim'};
results.png = true();
results.csv = true();
results.p = 0.01;
results.k = 0;
results.MC = 'none';
results.binary = true();
results.montage.do = true();
results.montage.slices = -4:2:16;
results.montage.orientation = 'axial';
% results.montage.background = struct('suffix', 'T1w', ...
%                                     'desc', 'preproc', ...
%                                     'modality', 'anat');
results.nidm = true();

opt.results = results;

bidspm(bids_dir, output_dir, 'dataset', ...
       'participant_label', subject_label, ...
       'action', 'results', ...
       'preproc_dir', preproc_dir, ...
       'model_file', model_file,...
       'task', task,...
       'space', space, ...
       'fwhm', 6,...
       'concatenate', false,...
       'options', opt);
