function [opt] = mvpa_chooseMask(opt)

opt.maskName = [];

switch opt.mask

    case 'SLpTFCE_eyemove_new'

        opt.dir.rois = '/Volumes/ssd/num_output/derivatives/bidspm-rois/group/SLpTFCE_eyemove_new';
        opt.maskName = {'group_hemi-L_space-MNI_label-hIP4_vox-300.nii', ...
            'group_hemi-L_space-MNI_label-hIP8_vox-300.nii', ...
            'group_hemi-L_space-MNI_label-V3A_vox-300.nii', ...
            'group_hemi-R_space-MNI_label-precentral_vox-300.nii', ...
            'group_hemi-R_space-MNI_label-hIP2_vox-300.nii', ...
            'group_hemi-R_space-MNI_label-hIP3_vox-300.nii', ...
            'group_hemi-R_space-MNI_label-hIP4_vox-300.nii'};

        opt.maskLabel = {'LhIP4', 'LhIP8', ...
            'LV3A', 'Rprecentral', 'RhIP2', ...
            'RhIP3', 'RhIP4'};

end
end
